name: Docker Image

on:
  - pull_request
  - push

jobs:
  tests:
    name: Build Docker Image
    runs-on: ubuntu-20.04
    env:
      COMPOSE_DOCKER_CLI_BUILD: "1"
      DOCKER_BUILDKIT: "1"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker build
        run: |
          docker build --build-arg=BUILD_SOURCE=prebuilt .

# vim:ft=yaml:et:ts=2:sw=2
